### ISSUE TITLE
screen location of buttons or any clickable links or areas.

### ISSUE THREAD

**Issue by xriss** [notshi/seance#2]
Assuming a portrait orientation.

Make sure all buttons can be reached by someone standing at the bottom edge of a large screen without exertion.

Arbitrary decision: Place buttons within bottom 20% of screen?

Maybe have bottom part of screen always a big button(s) so no need to reach an exact part.

**Comment by notshi** [comment]
All buttons are now huge and at the bottom.

Will need further testing with actual hardware when that arrives.
